export const USER_LOGGED = "USER_LOGGED"
export const USER_LOGOUT = "USER_LOGOUT"

export const RECORD_LIST = "RECORD_LIST"
export const RECORD_LOADING = "RECORD_LOADING"
export const RECORD_ERROR = "RECORD_ERROR"