export const USER_LOGGED = "USER_LOGGED"
export const USER_LOGOUT = "USER_LOGOUT"

export const RECORD_LIST = "RECORD_LIST"
export const ADD_RECORD = "ADD_RECORD"
export const DELETE_RECORD = "DELETE_RECORD"
export const UPDATE_RECORD = "UPDATE_RECORD"
export const RECORD_LOADING = "RECORD_LOADING"
export const RECORD_ERROR = "RECORD_ERROR"